### ISSUE TITLE
Convenience function to output what to order for the best design

### ISSUE THREAD

**Issue by matthiasheinig** [heiniglab/scPower#10]
When optimizing power for a given budget it would be nice to have a function that returns what one should order to run the experiment with the optimal design: how many illumina flowcells and 10X library prep kits?

**Comment by KatharinaSchmid** [comment]
Thanks for the suggestion, such a function is now added to the package (version 1.0.2), called `print_optimalDesign_10X()`. It takes the result data.frame from the optimization function `optimize.constant.budget()` as input.
