### ISSUE TITLE
number of 10X reactions per kit as a parameter

### ISSUE THREAD

**Issue by matthiasheinig** [heiniglab/scPower#11]
10X now sells the 4rxn kits. therefore it would be great have the number of reactions as a parameter in the functions `sampleSizeBudgetCalculation` and `optimize.constant.budget` and not always use the hard coded number of 6 rxns

**Comment by KatharinaSchmid** [comment]
Thanks for the suggestion, this parameter `reactionsPerKit` is added now to all necessary functions in the package (version 1.0.2), for example for budget calculation and optimization.
