### ISSUE TITLE
Shiny site http://scpower.helmholtz-muenchen.de/ seems to be down

### ISSUE THREAD

**Issue by pcm32** [heiniglab/scPower#22]
Hi and thanks for this great tool! I wanted to try it on the hosted shiny app, but doesn't seem to be working :-(.

**Comment by pcm32** [comment]
I get:

> Gateway Timeout
Server error - server 146.107.6.166 is unreachable at this moment.
>
> Please retry the request or contact your administrator.

**Comment by KatharinaSchmid** [comment]
Hi,
thank you both for reporting the issue. Unfortunately, we currently a problem with the server that hosts the website. We are working on it, but it will probably take some more time until we can restore the website. In the meantime, a workaround is calling the shiny app directly from the R package. For this, first the package needs to be installed in R:

```
install.packages("devtools")
devtools::install_github("heiniglab/scPower")
```

And afterwards, the app can be launched with:

```
library(scPower)
runShiny()
```
Sorry for the inconvenience. I hope we can fix the website soon.

Best regards,
Katharina

**Comment by Cem-Gulec** [comment]
Hello everyone, since the shiny server is back online again, I am closing this issue. Thank you for your kind interest!
