### ISSUE TITLE
How to use scPower to find the raw cell type

### ISSUE THREAD

**Issue by SELECT-FROM** [heiniglab/scPower#27]
Hello, I currently have a dataset. How can I use scPower to obtain which specific cells belong to the rare cell type?

**Comment by KatharinaSchmid** [comment]
Hi, 
sorry, I am a bit confused by your question. scPower was developed for experimental design, so how to best generate a new dataset, not for data analysis of existing datasets. But maybe I understand your questions wrong, can you elaborate it a bit more? If you want to identify rare cell types in your dataset, you could have a look at this tool: https://github.com/ScialdoneLab/CIARA
Best,
Katharina

**Comment by SELECT-FROM** [comment]
Hello,
Thank you for your answer. My previous understanding was indeed problematic. Thank you for your correction and suggestions. Once again, thank you for your answer.
Best
