### ISSUE TITLE
Question about nSample size in power.de

### ISSUE THREAD

**Issue by jig4003** [heiniglab/scPower#4]
Hello, thanks for the package.
I am using the "power.sameReadDepth.withDoublets" to calculate power for scRNA-Seq DE analysis. My understanding about the argument "nSamples" means the total sample size, meaning n0 + n1 in a two group setting. 
However, when I look closely into your source file "power.R", I am confused about the input argument nSamples for power.de function, which is called by the fdr.optimization function (starting line 1919 in power.R):
if(type=="de"){
    power<-sapply(1:length(es.vector), function(i)
      power.de(floor(nSamples/2),mean.vector[i],
               es.vector[i],1/disp.vector[i],x,
               ssize.ratio=ssize.ratio.de))
}
Here, why do you have to divide nSamples by 2? In the help document for power.de, it says nSamples is "Total samples size (n0 + n1), group balancing defined by size.ratio". Also, in the rest of calls of power.de, the nSamples is never divided by 2 again. Is this a bug or I am missing something?

Thank you very much for your time

**Comment by KatharinaSchmid** [comment]
Hi, thanks a lot for reporting this issue. You are right, it is a small bug, that happened recently when I introduced the ssize.ratio.de argument (before it was always balanced groups and I gave power.de only group size of group0, so it made sense). I corrected it now in the newest version 1.0.1. Interestingly, the difference caused where so small in our analysis that I did not notice it myself.
