### ISSUE TITLE
Please add R and package version requirements

### ISSUE THREAD

**Issue by hunter-moseley** [heiniglab/scPower#7]
Please add R and package version requirements.

I cannot install the required packages with my default version of R and I am not sure which version of R to download and install to make this package work.

**Comment by KatharinaSchmid** [comment]
Hi Hunter,

thanks for your feedback. We have already specified the R version (at least 3.3) and the package versions of packages that we had issues with in the DESCRIPTION file (https://github.com/heiniglab/scPower/blob/master/DESCRIPTION). So far, we had no other issues with versions, but it could very well be that we missed something. Could you specify what your error is when installing the package (exact error message) and which R version you currently use?

Best regards,
Katharina

**Comment by KatharinaSchmid** [comment]
Sorry, I don’t know exactly how to solve your issue, as it is nothing that I can fix in scPower. But a few suggestions, maybe one of them is helpful:

- If you don’t want to override your current R environment, I use conda to maintain multiple R versions at the same time, I can really recommend this, it might also help with installing openssl/devtools (there are of course other similar solutions, e.g. docker)
- The R package is more powerful, but we host the basic functionalities of scPower also on a website. So far it contains only a small set of priors from PBMC data (we are working on extending it), but it could still be helpful for you: http://scpower.helmholtz-muenchen.de
- I developed scPower on R3.5.1, it still runs there without any problems, maybe it helps to specify the devtools version I used there

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.7

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.2.1 usethis_1.5.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4        magrittr_2.0.1    pkgload_1.0.2     R6_2.5.0         
 [5] rlang_0.4.11      fansi_0.4.1       tools_3.5.0       pkgbuild_1.0.8   
 [9] sessioninfo_1.1.1 cli_2.0.2         withr_2.4.2       ellipsis_0.3.2   
[13] remotes_2.1.0     assertthat_0.2.1  digest_0.6.25     rprojroot_1.3-2  
[17] crayon_1.4.1      processx_3.4.2    callr_3.4.3       fs_1.3.2         
[21] ps_1.3.3          testthat_2.3.2    memoise_1.1.0     glue_1.3.2       
[25] compiler_3.5.0    desc_1.2.0        backports_1.1.5   prettyunits_1.1.1
